version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "Nikehurley13."
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  python-app:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres-data:
    driver: local
